opentelemetry-operator:
  # Basic operator configuration
  replicaCount: 1
  
  # Manager configuration
  manager:
    autoInstrumentationImage:
      python: 
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python
        tag: latest
      nodejs:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs
        tag: latest
    autoInstrumentation:
      nodejs:
        enabled: true
      python:
        enabled: true
