apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: demo-dotnet
            path: apps/demo
            namespace: apps
            cluster: in-cluster
            type: app
            owner: dev-team
            syncwave: "3"

  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
      labels:
        gitops.taz.dev/owner: "{{.owner}}"
        gitops.taz.dev/type: "{{.type}}"
        gitops.taz.dev/cluster: "{{.cluster}}"
        gitops.taz.dev/namespace: "{{.namespace}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.syncwave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Tazmainiandevil/gitops.tracing.git
        path: "{{.path}}"
        targetRevision: main
      destination:
        namespace: "{{.namespace}}"
        name: "{{.cluster}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
