apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dotnet
  namespace: apps
  annotations:
    instrumentation.opentelemetry.io/inject-dotnet: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dotnet
  template:
    metadata:
      labels:
        app: demo-dotnet
    spec:
      containers:
        - name: demo-dotnet
          image: demo-dotnet:latest
          ports:
            - containerPort: 8080